"""Regenerate LaTeX table fragments from data/results/*.json.

Writes three files into latex/tables/:
  - length.tex    : F1 length-bias Spearman table (from length_ablation.json)
  - halluc.tex    : F2 per-agent error-class distribution (from error_taxonomy.json)
  - irt.tex       : F3 agent ability under BT-Elo vs IRT-theta
                    (from irt_calibration.json + arena_elo_ED.json)

All three are standalone tabular environments so findings.tex can
`\input{tables/length.tex}` etc. Re-running this script is idempotent — same
input produces the same output.

Re-run after any rescore so the paper tracks the latest numbers.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "data" / "results"
OUT_DIR = ROOT / "latex" / "tables"
OUT_DIR.mkdir(parents=True, exist_ok=True)


PILLAR_LABELS = {
    "markdown_structure": r"\texttt{markdown\_structure}",
    "citation":           r"\texttt{citation}",
    "fact_kg":            r"\texttt{fact\_kg}",
    "llm_judge":          r"\texttt{llm\_judge}",
    "checklist":          r"\texttt{checklist}",
    "evidence_density":   r"\texttt{evidence\_density}",
    "efficiency":         r"\texttt{efficiency}",
    "composite":          r"\texttt{composite}",
}


def _escape_agent(name: str) -> str:
    """Underscores are fine inside \texttt{}, but hyphens-in-braces are safer."""
    return r"\texttt{" + name + r"}"


def _flag_for(rho: float) -> str:
    # Chinese flags matching the paper body
    a = abs(rho)
    if a < 0.4:
        return "正常"
    if a < 0.6:
        return r"\textbf{可疑}"
    return r"\textbf{强相关}"


def _format_rho(rho):
    if rho is None:
        return "---"
    return f"${'+' if rho >= 0 else '-'}{abs(rho):.2f}$"


def gen_length() -> None:
    src = json.loads((RESULTS / "length_ablation.json").read_text())
    pillars = src["pillars"]

    rows = []
    # Fixed order for readability
    order = [
        "markdown_structure", "citation", "fact_kg", "llm_judge",
        "checklist", "evidence_density", "efficiency", "composite",
    ]
    for key in order:
        info = pillars.get(key, {})
        rho = info.get("spearman")
        p = info.get("p_value")
        flag = info.get("flag")
        if flag is None or rho is None:
            row = f"{PILLAR_LABELS[key]} & --- & --- & {flag or '---'} \\\\"
        else:
            rho_disp = _format_rho(rho)
            p_disp = f"{p:.3f}" if p is not None else "---"
            row = (f"{PILLAR_LABELS[key]} & {rho_disp} & {p_disp} & "
                   f"{_flag_for(rho)} \\\\")
        rows.append(row)

    body = (
        "% regenerated by latex/generate_tables.py\n"
        r"\begin{tabular}{lrrc}" + "\n"
        r"  \toprule" + "\n"
        r"  维度 & Spearman $\rho$ & $p$ 值 & 标志 \\" + "\n"
        r"  \midrule" + "\n"
        + "\n".join("  " + r for r in rows) + "\n"
        r"  \bottomrule" + "\n"
        r"\end{tabular}" + "\n"
    )
    (OUT_DIR / "length.tex").write_text(body)
    print(f"  wrote {OUT_DIR / 'length.tex'} ({len(rows)} rows)")


def gen_halluc() -> None:
    src = json.loads((RESULTS / "error_taxonomy.json").read_text())
    by_agent = src["summary"]["by_agent_primary"]
    # Drop synthetic smoke/test agents (those with low n)
    rows = []
    total = [0, 0, 0, 0, 0]  # ok, tool, halluc, format, timeout
    for agent in sorted(by_agent):
        c = by_agent[agent]
        ok = c.get("ok", 0)
        halluc = c.get("hallucination_url", 0)
        fmt = c.get("format_error", 0)
        timeout = c.get("timeout_or_empty", 0)
        tool = c.get("tool_misuse", 0)
        n = ok + halluc + fmt + timeout + tool
        if n < 3:          # skip smoke runs
            continue
        total[0] += ok
        total[1] += tool
        total[2] += halluc
        total[3] += fmt
        total[4] += timeout
        # Bold the pure-halluc agents
        emphasize = halluc == n and halluc >= 3
        label = (r"\texttt{\textbf{" + agent + r"}}" if emphasize
                 else r"\texttt{" + agent + r"}")
        halluc_cell = r"\textbf{" + str(halluc) + r"}" if emphasize else str(halluc)
        rows.append(f"  {label} & {ok} & {tool} & {halluc_cell} & "
                    f"{fmt} & {timeout} & {n} \\\\")

    tot_n = sum(total)
    body = (
        "% regenerated by latex/generate_tables.py\n"
        r"\begin{tabular}{lrrrrrr}" + "\n"
        r"  \toprule" + "\n"
        r"  Agent & 正常 & 工具误用 & URL 幻觉 & 格式错 & 超时 & 总计 \\" + "\n"
        r"  \midrule" + "\n"
        + "\n".join(rows) + "\n"
        r"  \midrule" + "\n"
        f"  总计 & {total[0]} & {total[1]} & {total[2]} & "
        f"{total[3]} & {total[4]} & {tot_n} \\\\" + "\n"
        r"  \bottomrule" + "\n"
        r"\end{tabular}" + "\n"
    )
    (OUT_DIR / "halluc.tex").write_text(body)
    print(f"  wrote {OUT_DIR / 'halluc.tex'} ({len(rows)} agents, "
          f"{total[2]}/{tot_n} halluc)")


def gen_irt() -> None:
    irt = json.loads((RESULTS / "irt_calibration.json").read_text())
    agents = irt["agents"]
    thetas = irt["params"]["theta"]

    # Try to pair with BT-Elo values.
    # Prefer arena_final.json (new, from build_final_leaderboard.py) over
    # arena_elo_ED.json (old legacy). Accept both key names.
    elo_map: dict[str, float] = {}
    for name in ("arena_final.json", "arena_elo_ED.json"):
        p = RESULTS / name
        if not p.exists():
            continue
        try:
            d = json.loads(p.read_text())
        except Exception:
            continue
        m = d.get("composite_elo") or d.get("composite_elo_new") or {}
        if m:
            elo_map = {
                k: (v.get("elo") if isinstance(v, dict) else v)
                for k, v in m.items()
            }
            break

    paired = sorted(zip(agents, thetas), key=lambda x: -x[1])
    rows = []
    for a, th in paired:
        elo = elo_map.get(a)
        elo_disp = f"{elo:.0f}" if elo is not None else "---"
        th_disp = f"${'+' if th >= 0 else '-'}{abs(th):.2f}$"
        rows.append(f"  {_escape_agent(a)} & {elo_disp} & {th_disp} \\\\")

    body = (
        "% regenerated by latex/generate_tables.py\n"
        r"\begin{tabular}{lrr}" + "\n"
        r"  \toprule" + "\n"
        r"  Agent & BT Elo & IRT $\theta$ \\" + "\n"
        r"  \midrule" + "\n"
        + "\n".join(rows) + "\n"
        r"  \bottomrule" + "\n"
        r"\end{tabular}" + "\n"
    )
    # (Agent 列与 theta / Elo 列都是英文数字,不翻译)
    (OUT_DIR / "irt.tex").write_text(body)
    print(f"  wrote {OUT_DIR / 'irt.tex'} ({len(rows)} agents)")


def main() -> int:
    print(f"regenerating latex tables into {OUT_DIR}")
    gen_length()
    gen_halluc()
    gen_irt()
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
