"""Gates G1 (oracle tops out) + G2 (shell zeroes) over all 100 answer keys.

G1: a report that does exactly what the answer key demands (the oracle report
mechanically generated by ``src/eval/oracle_report.py``) must saturate every
axis the observable world allows:

    reach = 1.0, fact > 0, completeness == the achievable ceiling, EXACTLY.

"Achievable ceiling" and not the literal 1.0 of GOAL_GATES_V1 because three
frozen-semantics facts make a literal 1.0 unreachable for ANY report today;
the literal assertion is kept as an expected-red xfail pointing at the
docs/SPEC_ISSUES.md entries (freeze order: semantics are not touched here):

  * the forum virtual slot: no forum thread page exists in any page cache
    fixture, so the slot is uncoverable (SPEC_ISSUES section 1 "论坛是否入分" +
    section 2 "page cache 供给链失修");
  * short-subject concepts ("Tea"): the scorer's ``_subject_discussed``
    requires a strong token (>=4 chars or a digit), which such subjects never
    have (SPEC_ISSUES section 4 G1 note);
  * title-only stub pages in the capture ("Input lag"): shorter than the
    scorer's 400-char containment window, ungroundable by construction.

The EXACT-equality assertion against the generator's by-construction plan is
the real gate: the scorer must credit precisely the nuggets the oracle made
coverable, no more (no phantom credit) and no fewer (no silent zeroing).

G2: a shell report with no checkable content must score 0 on every axis and
on composed truth, for every task.

Marked ``gates`` (deselected by default; run via scripts/run_gates.py).
Deterministic: committed answer keys + committed cache fixture; no network,
no clock, no randomness.
"""

from __future__ import annotations

import pytest

import src.eval.decidable_scorer as ds
from src.eval.answer_key import AnswerKey
from src.eval.oracle_report import CONCEPT_CACHE_REL, build_oracle_report

pytestmark = pytest.mark.gates

SHELL_REPORT = (
    "# Report\n\n"
    "This report has nothing checkable to say about anything at all. It cites "
    "no sources, names no products, and asserts no prices, ratings or facts."
)

NO_CACHE_SKIP = (
    f"concept page cache fixture absent ({CONCEPT_CACHE_REL}): the concept "
    "share of completeness is unverifiable on this checkout and is skipped "
    "EXPLICITLY; structured coverage, fact and reach are still asserted."
)


@pytest.fixture(scope="module")
def oracle_runs(gates_key_paths, gates_registry, gates_concept_cache,
                gates_page_stats):
    """Score the oracle report once per task; every G1 test asserts over this."""
    cache = gates_concept_cache or {}
    runs = []
    for path in gates_key_paths:
        ak = AnswerKey.load(path)
        rep = build_oracle_report(ak, cache=cache, registry=gates_registry)
        generic = ds.build_generic_tokens(ak)
        comp, cd = ds.score_completeness(
            rep.markdown, ak, generic=generic, cache=cache,
            page_stats=gates_page_stats, registry=gates_registry)
        # Ruling #6 (docs/SPEC_DECISIONS.md): the diagnostic cache_policy score
        # (ruling #2) is what the literal-1.0 attempt is measured against -- it
        # withholds the cache-blind forum slot instead of zeroing it.
        comp_diag, cd_diag = ds.score_completeness(
            rep.markdown, ak, generic=generic, cache=cache,
            page_stats=gates_page_stats, registry=gates_registry,
            cache_policy="diagnostic")
        fact, fd = ds.score_fact_support(rep.markdown, ak, generic=generic)
        reach, rd = ds.score_reachability(
            rep.cited_urls, cache, registry=gates_registry)
        runs.append({
            "tid": ak.task_id, "plan": rep.plan,
            "comp": comp, "cd": cd, "comp_diag": comp_diag, "cd_diag": cd_diag,
            "fact": fact, "fd": fd, "reach": reach, "rd": rd,
        })
    return runs


def _failures(runs, predicate, describe):
    out = []
    for r in runs:
        if not predicate(r):
            out.append(f"{r['tid']}: {describe(r)}")
    return out


# ---------------------------------------------------------------------------
# G1
# ---------------------------------------------------------------------------

def test_g1_oracle_reach_tops_out(oracle_runs):
    """Every citation in the oracle report is an in-corpus content page, so
    reach must be exactly 1.0 on every task."""
    bad = _failures(
        oracle_runs,
        lambda r: r["reach"] == pytest.approx(1.0, abs=1e-9),
        lambda r: f"reach={r['reach']:.4f} detail={r['rd']}")
    assert not bad, "G1 reach<1.0 on:\n" + "\n".join(bad)


def test_g1_oracle_fact_axis_positive(oracle_runs):
    """The oracle makes one inline-cited DB-true price claim per task, so the
    fact axis must be active and strictly positive everywhere."""
    bad = _failures(
        oracle_runs,
        lambda r: r["fact"] > 0.0 and r["fd"].get("supported", 0) >= 1
        and r["fd"].get("contradicted", 0) == 0,
        lambda r: (f"fact={r['fact']:.4f} supported={r['fd'].get('supported')} "
                   f"contradicted={r['fd'].get('contradicted')} "
                   f"uncited={r['fd'].get('supported_uncited')} "
                   f"fact_url={r['plan'].get('fact_url')}"))
    assert not bad, "G1 fact axis inert or contradicted on:\n" + "\n".join(bad)


def test_g1_oracle_structured_share_fully_covered(oracle_runs):
    """Every structured (buyer_sentiment / price / rating / thread_score)
    nugget the oracle stated must be credited by the scorer: this is the share
    the 35-nugget bracket-label bug used to silently zero."""
    def ok(r):
        cbp = r["cd"].get("covered_by_predicate", {})
        want = r["plan"]["struct_by_predicate"]
        return all(cbp.get(p, 0) == n for p, n in want.items())

    bad = _failures(
        oracle_runs, ok,
        lambda r: (f"covered_by_predicate={r['cd'].get('covered_by_predicate')} "
                   f"!= planned {r['plan']['struct_by_predicate']}"))
    assert not bad, "G1 structured nuggets dropped on:\n" + "\n".join(bad)


def test_g1_oracle_concept_share_fully_covered(oracle_runs, gates_concept_cache):
    """Every concept the cache makes groundable (real page text, creditable
    subject) must be credited -- and ONLY those (a phantom concept credit is as
    much a gate failure as a dropped one). Skips explicitly without the box
    cache fixture."""
    if gates_concept_cache is None:
        pytest.skip(NO_CACHE_SKIP)

    def ok(r):
        got = r["cd"].get("covered_by_predicate", {}).get("concept_coverage", 0)
        return got == len(r["plan"]["concept_covered_urls"])

    bad = _failures(
        oracle_runs, ok,
        lambda r: (
            f"concept credited="
            f"{r['cd'].get('covered_by_predicate', {}).get('concept_coverage', 0)}"
            f" != planned {len(r['plan']['concept_covered_urls'])} "
            f"(uncreditable={len(r['plan']['concept_uncreditable_urls'])} "
            f"stub={len(r['plan']['concept_stub_page_urls'])} "
            f"uncached={len(r['plan']['concept_uncovered_urls'])})"))
    assert not bad, "G1 concept share mismatch on:\n" + "\n".join(bad)


def test_g1_oracle_completeness_equals_achievable_ceiling(oracle_runs,
                                                          gates_concept_cache):
    """Completeness must EXACTLY equal the generator's by-construction ceiling:
    higher means phantom credit, lower means silent zeroing. Without the cache
    fixture the ceiling is the structured-only one and the concept share is
    skipped by test_g1_oracle_concept_share_fully_covered; the equality here
    still holds and is still asserted."""
    bad = _failures(
        oracle_runs,
        lambda r: r["comp"] == pytest.approx(
            r["plan"]["expected_completeness"], abs=1e-9),
        lambda r: (f"comp={r['comp']:.4f} != "
                   f"expected {r['plan']['expected_completeness']:.4f} "
                   f"(covered={r['cd'].get('covered')} "
                   f"planned={r['plan']['expected_covered']} "
                   f"denom={r['plan']['denom']})"))
    assert not bad, "G1 completeness != achievable ceiling on:\n" + "\n".join(bad)


def test_g1_oracle_diagnostic_completeness_one_except_stub_pages(oracle_runs):
    """The achievement of rulings #2 + #5 + the short-topic fix, as a GREEN gate.

    Under the diagnostic cache_policy (ruling #2) the cache-blind forum slot is
    WITHHELD from the denominator instead of zeroing completeness, and the
    short-topic fix (ruling #5) freed the last uncreditable concepts. So every
    oracle report now reaches literal completeness == 1.0 EXACTLY, with a single
    documented exception class: a task carrying a title-only stub concept page
    (the page IS cached but its whole body is shorter than the 400-char
    containment window, so no report can ground a quote). Those pages are a
    page-cache FIXTURE defect to be excised at key-construction time
    (build_answer_keys lane, docs/SPEC_DECISIONS.md '车道追加条目'), not a scorer
    change; the diagnostic withhold only covers a MISSING page, not a cached-but
    -too-short one. This gate pins that the ONLY tasks short of 1.0 are exactly
    the stub-page ones, and by the exact residual."""
    bad = []
    for r in oracle_runs:
        n_stub = len(r["plan"]["concept_stub_page_urls"])
        if n_stub == 0:
            if r["comp_diag"] != pytest.approx(1.0, abs=1e-9):
                bad.append(f"{r['tid']}: no stub page yet comp_diag="
                           f"{r['comp_diag']:.4f} (cd={r['cd_diag']})")
        else:
            # the shortfall must be exactly the uncoverable stub slots
            denom = r["cd_diag"]["k_effective"]
            expected = max(denom - n_stub, 0) / denom if denom else 0.0
            if r["comp_diag"] != pytest.approx(expected, abs=1e-9):
                bad.append(f"{r['tid']}: {n_stub} stub page(s), comp_diag="
                           f"{r['comp_diag']:.4f} != expected {expected:.4f}")
    assert not bad, ("G1 diagnostic completeness not 1.0-except-stub on:\n"
                     + "\n".join(bad))


@pytest.mark.xfail(
    strict=False,
    reason=(
        "GOAL_GATES_V1 asks completeness == 1.0 literally for EVERY task. Under "
        "the diagnostic cache_policy (ruling #2) plus the short-topic fix "
        "(ruling #5), 99/100 tasks now reach it exactly: the forum virtual slot "
        "is WITHHELD (no cached thread to ground) and short-subject concepts "
        "('Tea') are credited by word-boundary matching. The sole residual is a "
        "title-only stub concept page ('Input lag', dr_cross_deep_0038): the "
        "page IS cached but its whole body is shorter than the 400-char "
        "containment window, so no report can ground a quote and the diagnostic "
        "withhold (which covers a MISSING page, not a cached-but-too-short one) "
        "cannot remove it. Excising such stub pages at key-construction time is "
        "the build_answer_keys lane (docs/SPEC_DECISIONS.md '车道追加条目'), out "
        "of the scorer's scope; until then this universal assertion stays red by "
        "exactly that one slot. The green gate is "
        "test_g1_oracle_diagnostic_completeness_one_except_stub_pages above."),
)
def test_g1_oracle_completeness_literal_one(oracle_runs):
    bad = _failures(
        oracle_runs,
        lambda r: r["comp_diag"] == pytest.approx(1.0, abs=1e-9),
        lambda r: f"comp_diag={r['comp_diag']:.4f}")
    assert not bad, "completeness < 1.0 on:\n" + "\n".join(bad)


# ---------------------------------------------------------------------------
# G2
# ---------------------------------------------------------------------------

def test_g2_shell_scores_zero_on_every_axis(gates_key_paths, gates_registry):
    """A report with no checkable content earns 0 on reach, pof, fact,
    completeness, spec AND composed truth, on every task. Any nonzero is a
    laundering hole."""
    empty_stats = ds.build_page_stats({})
    bad = []
    for path in gates_key_paths:
        ak = AnswerKey.load(path)
        s = ds.score_report(SHELL_REPORT, ak, cache={}, registry=gates_registry,
                            page_stats=empty_stats)
        axes = {
            "reach": s.reach, "pof": s.proof_of_fetch,
            "fact": s.fact_support, "completeness": s.completeness,
            "spec": s.spec, "truth": s.truth,
        }
        nonzero = {k: v for k, v in axes.items() if v != 0.0}
        if nonzero:
            bad.append(f"{ak.task_id}: nonzero axes {nonzero}")
    assert not bad, "G2 shell earned score on:\n" + "\n".join(bad)


def test_g2_shell_zero_is_observed_not_withheld(gates_key_paths, gates_registry):
    """The shell's zeros must be OBSERVED zeros (scored, with detail), not the
    product of a withhold path: completeness reports pool>0 with covered==0 and
    fact reports no_checkable_claims. Guards the 'withhold never scores 0 /
    0 always means observed-and-bad' invariant from the G2 side."""
    bad = []
    for path in gates_key_paths:
        ak = AnswerKey.load(path)
        comp, cd = ds.score_completeness(SHELL_REPORT, ak, cache={},
                                         registry=gates_registry)
        fact, fd = ds.score_fact_support(SHELL_REPORT, ak)
        if not (comp == 0.0 and cd.get("pool", 0) > 0 and cd.get("covered") == 0):
            bad.append(f"{ak.task_id}: completeness detail not an observed zero: "
                       f"comp={comp} pool={cd.get('pool')} covered={cd.get('covered')}")
        if not (fact == 0.0 and fd.get("reason") == "no_checkable_claims"
                and fd.get("fact_active") is False):
            bad.append(f"{ak.task_id}: fact detail not an observed zero: "
                       f"fact={fact} reason={fd.get('reason')}")
    assert not bad, "G2 zero-semantics broken on:\n" + "\n".join(bad)
