"""Rebuild fact_kg oracle with task-intent-aware filtering.

The current oracle (data/golden/dr_cross_v3_*.json) is auto-generated by
`envs/cross_site/oracle_dr_v3/run_all_oracles.py` which takes the top-N
products by category without filtering by task constraints (price cap,
category relevance, etc.). That produces obvious artefacts — e.g. task
0005 "$500 home office" oracle includes a $607 Epson printer; task 0007
"budget home cook" oracle includes "Magic Home Nightstands". A good
agent that *correctly* filters gets penalised by `fact_kg` recall.

This script rebuilds the oracle per task by:
  1. Loading the task config (`intent` + explicit constraints).
  2. Extracting structured constraints from intent (budget ceiling,
     category allowlist, min-rating) via regex + heuristics.
  3. Re-querying the sandbox (Magento + Postmill) with those filters.
  4. Emitting only products that satisfy the filters.

Usage:
    python scripts/rebuild_oracle_filtered.py           # all tasks
    python scripts/rebuild_oracle_filtered.py 0005 0007 # subset

Must run on the server that can reach http://localhost:7770 (i.e. remote
WSL where Magento + Postmill live).
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import requests
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]
SHOPPING = os.environ.get("SHOPPING", "http://localhost:7770")
REDDIT = os.environ.get("REDDIT", "http://localhost:9999")

TASKS_DIR = ROOT / "data" / "tasks" / "deep_research" / "cross_site"
GOLDEN_DIR = ROOT / "data" / "golden"


# ---------------------------------------------------------------------------
# Constraint extraction from intent
# ---------------------------------------------------------------------------

_BUDGET_RE = re.compile(r"\$\s*(\d{2,4})(?:\s*(?:budget|cap|ceiling|total|max))?", re.I)
_PRICE_RANGE_RE = re.compile(r"\$\s*(\d{1,4})\s*[-–]\s*\$?\s*(\d{1,4})", re.I)

_CATEGORY_HINTS: dict[str, list[str]] = {
    "home-kitchen":       ["kitchen", "pots", "pans", "utensil", "cooking", "stove", "knife"],
    "grocery-gourmet-food": ["grocery", "food", "pantry", "staple", "ingredient"],
    "office-products":    ["office", "desk", "chair", "work"],
    "electronics":        ["electronic", "gadget", "device"],
    "video-games":        ["gaming", "pc game", "console"],
    "health-household":   ["health", "household", "cleaning"],
    "cell-phones-accessories": ["phone", "mobile", "charger", "case"],
    "beauty-personal-care": ["beauty", "skincare", "cosmetic"],
    "sports-outdoors":    ["sports", "outdoor", "fitness"],
    "toys-games":         ["toy", "game", "board game"],
}


def _budget_from_intent(intent: str) -> float | None:
    """Extract a budget ceiling from task intent, e.g. "$500 home office"."""
    m = _BUDGET_RE.search(intent)
    if m:
        try:
            v = float(m.group(1))
            # Filter out low nuisance matches like "$30" which likely mean
            # "a single item at $30", not the total budget.
            if v >= 50:
                return v
        except Exception:
            pass
    return None


def _price_range_from_intent(intent: str) -> tuple[float, float] | None:
    m = _PRICE_RANGE_RE.search(intent)
    if not m:
        return None
    try:
        lo, hi = float(m.group(1)), float(m.group(2))
        return (lo, hi)
    except Exception:
        return None


def _category_relevance(intent: str, category: str, product_name: str) -> bool:
    """Is this product plausibly on-topic given intent + its own name?"""
    q = (intent + " " + product_name).lower()
    hints = _CATEGORY_HINTS.get(category, [])
    # Product must share at least one category hint OR the intent
    # mentions the category token itself.
    if not hints:
        return True
    for h in hints:
        if h in q:
            return True
    # Last-resort: reject if product name clearly belongs to an unrelated
    # physical-category (e.g. "Nightstand" in a kitchen build).
    if "nightstand" in product_name.lower() and "kitchen" in intent.lower():
        return False
    if "tv stand" in product_name.lower() and "kitchen" in intent.lower():
        return False
    return True


# ---------------------------------------------------------------------------
# Magento scrape
# ---------------------------------------------------------------------------

def _scrape_category(category_slug: str, max_items: int = 40) -> list[dict]:
    url = f"{SHOPPING}/{category_slug}.html?product_list_limit=all"
    try:
        r = requests.get(url, timeout=30)
        if r.status_code >= 400:
            return []
    except Exception:
        return []
    soup = BeautifulSoup(r.text, "html.parser")
    items = []
    for el in soup.select("li.item.product.product-item, .products-grid .product-item")[:max_items]:
        a = el.select_one("a.product-item-link, .product-item-name a")
        if not a:
            continue
        name = a.get_text(strip=True)
        url = a.get("href") or ""
        price = None
        p_el = el.select_one("[data-price-amount]")
        if p_el and p_el.get("data-price-amount"):
            try:
                price = float(p_el["data-price-amount"])
            except Exception:
                pass
        rating = None
        r_el = el.select_one("[title]")
        if r_el:
            m = re.search(r"(\d+)%", r_el.get("title") or "")
            if m:
                rating = int(m.group(1)) / 20
        items.append({
            "name": name, "url": url,
            "price": price, "rating": rating,
            "category": category_slug,
        })
    return items


# ---------------------------------------------------------------------------
# Oracle rebuild
# ---------------------------------------------------------------------------

def _rebuild_one_task(task_id: str) -> dict[str, Any]:
    cfg_path = TASKS_DIR / f"{task_id}.json"
    if not cfg_path.exists():
        return {"task_id": task_id, "error": "no task config"}
    cfg = json.loads(cfg_path.read_text())
    intent = cfg.get("intent", "")

    budget = _budget_from_intent(intent)
    price_range = _price_range_from_intent(intent)

    # Which shopping categories does the intent mention?
    intent_low = intent.lower()
    active_cats: list[str] = []
    for slug, hints in _CATEGORY_HINTS.items():
        if slug in intent_low or any(h in intent_low for h in hints):
            active_cats.append(slug)
    if not active_cats:
        # Fallback: try the category tokens from task config
        for site in cfg.get("sites", []):
            if site in _CATEGORY_HINTS:
                active_cats.append(site)

    triples: list[dict] = []
    for cat in active_cats[:5]:  # cap to avoid blowing up
        prods = _scrape_category(cat, max_items=60)
        for p in prods:
            if p.get("price") is None:
                continue
            # Budget filter
            if budget is not None and p["price"] > budget:
                continue
            # Price range filter (from e.g. "$30-100")
            if price_range is not None:
                lo, hi = price_range
                if p["price"] < lo or p["price"] > hi:
                    continue
            # Topic / category relevance filter
            if not _category_relevance(intent, cat, p["name"]):
                continue
            # Emit as (subject, predicate, object) triples
            subj = p["name"][:60]
            triples.append({"subject": subj, "predicate": "price", "object": f"{p['price']:.2f}"})
            if p.get("rating") is not None:
                triples.append({"subject": subj, "predicate": "rating", "object": f"{p['rating']:.2f}"})
            triples.append({"subject": subj, "predicate": "category", "object": cat})
            triples.append({"subject": subj, "predicate": "product_url", "object": p["url"][:80]})

    return {
        "task_id": task_id,
        "intent_excerpt": intent[:200],
        "budget_detected": budget,
        "price_range_detected": price_range,
        "active_categories": active_cats[:5],
        "n_triples": len(triples),
        "triples": triples,
    }


def main() -> None:
    subset = sys.argv[1:] if len(sys.argv) > 1 else None
    all_tasks = sorted(
        p.stem for p in TASKS_DIR.glob("dr_cross_v3_*.json")
        if not p.stem.endswith("_")
    )
    targets = [t for t in all_tasks if (subset is None or any(s in t for s in subset))]

    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)

    for tid in targets:
        r = _rebuild_one_task(tid)
        print(f"{tid}: budget={r.get('budget_detected')}  "
              f"range={r.get('price_range_detected')}  "
              f"cats={r.get('active_categories')}  "
              f"→ {r.get('n_triples')} triples")
        # Write oracle to a sibling file so we don't clobber the old one
        out = GOLDEN_DIR / f"{tid}.filtered.json"
        out.write_text(json.dumps(r["triples"], indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
