"""Pydantic models for deep-research task files.

Lightweight — mirrors the WebArena JSON shape with three new sections:
`report_schema`, `citation_policy`, and `eval.report_expected`. See
`DEEP_RESEARCH_TASK_SPEC.md` for the narrative spec.
"""

from typing import Any, Dict, List, Optional, Tuple

from pydantic import BaseModel, Field


class CitationPolicy(BaseModel):
    required_for: List[str] = Field(default_factory=list)
    must_be_in_domain: List[str] = Field(default_factory=list)
    min_distinct_sources: int = 1


class FieldConstraint(BaseModel):
    """One expected constraint on a single item inside a report list field."""

    name_contains: Optional[List[str]] = None
    name_regex: Optional[str] = None
    price_range: Optional[Tuple[float, float]] = None
    rating_min: Optional[float] = None
    url_regex: Optional[str] = None
    extra: Dict[str, Any] = Field(default_factory=dict)


class ReportExpected(BaseModel):
    """Whitelist of required facts the report must contain."""

    products: Optional[List[FieldConstraint]] = None
    facts: Optional[List[str]] = None
    numeric: Optional[Dict[str, Tuple[float, float]]] = None
    extra: Dict[str, Any] = Field(default_factory=dict)


class DREval(BaseModel):
    eval_types: List[str]
    report_expected: Optional[ReportExpected] = None
    source_count_min: Optional[int] = None
    reference_answers: Optional[Dict[str, Any]] = None
    reference_url: Optional[str] = None
    program_html: Optional[List[Dict[str, Any]]] = None


class DeepResearchTask(BaseModel):
    """v2 task — strict JSON `report_schema`, deprecated by `DeepResearchTaskV3`."""

    task_id: str = Field(..., pattern=r"^dr_[a-z]+_[0-9]{4}$")
    sites: List[str]
    intent: str
    start_url: str
    storage_state: Optional[str] = None
    require_login: bool = False

    report_schema: Dict[str, Any]
    citation_policy: CitationPolicy
    eval: DREval

    difficulty: Optional[int] = Field(None, ge=1, le=5)
    expected_steps: Optional[int] = Field(None, ge=1, le=50)
    author_notes: Optional[str] = None

    @classmethod
    def load(cls, path: str) -> "DeepResearchTask":
        import json as _json
        from pathlib import Path as _Path

        return cls.model_validate(_json.loads(_Path(path).read_text()))


# ---------------- v3 ----------------

class MarkdownReportSpec(BaseModel):
    """Quantitative lower bounds the agent's markdown report must clear.

    No section structure is enforced — the agent organizes paragraphs
    freely. We only check the report meets minimum length / citation /
    page-coverage thresholds. This is the v3 replacement for v2's
    rigid JSON `report_schema`.
    """

    min_words: int = Field(500, ge=50)
    max_words: int = Field(4000, ge=200)
    min_paragraphs: int = Field(3, ge=1)
    min_citations: int = Field(5, ge=1)
    min_pages_browsed: int = Field(3, ge=1)
    # When True, the verifier counts only inline `[text](url)` markdown
    # links toward `min_citations`; bare URLs in prose still count if False.
    require_markdown_links: bool = True


class GoldenSpec(BaseModel):
    """Where the KG-based golden answer for this task lives."""

    # Path (relative to repo root) to a JSON file with [{subject, predicate, object}, ...].
    # Generated by the task's Oracle. The fact_kg verifier consults this
    # plus the live DB for grounding agent claims.
    triples_path: Optional[str] = None
    # Hint about which DB tables / sites the agent's facts will land in,
    # so the triple_extractor can skip irrelevant predicates.
    expected_predicates: List[str] = Field(default_factory=list)


class DeepResearchTaskV3(BaseModel):
    """v3 deep-research task — long-form markdown output, KG golden answer.

    Differences from v2:
      - `report_schema` (rigid JSON) → `markdown_spec` (free-form markdown bounds)
      - `report_expected` (constraint envelope) → `golden` (KG triples + DB)
      - Adds `min_distinct_pages` to enforce multi-page browsing
      - Adds `coverage_checklist_path` pointer (DRACO ~15 binary criteria)
    """

    schema_version: str = Field(default="3.0.0", pattern=r"^3\.[0-9]+\.[0-9]+$")
    task_id: str = Field(..., pattern=r"^dr_[a-z]+_v3_[0-9]{4}$")
    sites: List[str] = Field(..., min_length=1)
    intent: str = Field(..., min_length=30)
    start_url: str
    storage_state: Optional[str] = None
    require_login: bool = False

    markdown_spec: MarkdownReportSpec
    citation_policy: CitationPolicy
    golden: GoldenSpec = Field(default_factory=GoldenSpec)

    # Path to per-task DRACO-style coverage checklist (~15 binary items)
    # Stored separately from this file to keep the task json scannable.
    coverage_checklist_path: Optional[str] = None

    difficulty: Optional[int] = Field(None, ge=1, le=5)
    expected_steps: Optional[int] = Field(None, ge=1, le=50)
    author_notes: Optional[str] = None

    @classmethod
    def load(cls, path: str) -> "DeepResearchTaskV3":
        import json as _json
        from pathlib import Path as _Path

        return cls.model_validate(_json.loads(_Path(path).read_text()))
